apiVersion: v1
kind: PersistentVolume
metadata:
  name: Bdata
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: Bdata
  azureFile:
    secretName: b-storage-secret
    shareName: buoydata
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000