apiVersion: v1
kind: PersistentVolume
metadata:
  name: meteo-secretfile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: meteoshare
  azureFile:
    secretName: meteo-storage-secret
    shareName: gtsm
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
